name = "chickenroadapp-com-es"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=chickenroadapp.com.es"
HMAC_KEY = "c452802ff16d4ee9960b3f736bddb982af2120d4730ddec7ce41807f256be5e2"
COOKIE_NAME = "on0"
PLAY_PATH = "try-now"
BUTTON_ID = "pc6b1d3a04018089e68f0518c3dc53403"
GATE_SALT = "e3ee6518caa94ea8"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "2pzj"
CTA_SELECTOR = ".play-button"
